#DOCKER-COMPOSE

networks:
  inception:
    name: "inception"
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build: requirements/mariadb/
    env_file: .env
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    build: requirements/wordpress/
    env_file: .env
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception
    build: requirements/nginx/
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: on-failure

volumes:
  wordpress:
    name: "wordpress"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  mariadb:
    name: "mariadb"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
